'use client';
import { useEffect, useState } from 'react';
import { X, Sparkles } from 'lucide-react';

type Props = {
  open: boolean;
  onClose: () => void;
  summary: string;
  isLoading: boolean;
  error: string | null;
};

export default function SummaryModal({ open, onClose, summary, isLoading, error }: Props) {
  const [visible, setVisible] = useState(false);

  useEffect(() => { setVisible(open); }, [open]);

  useEffect(() => {
    function onKey(e: KeyboardEvent) { if (e.key === 'Escape') onClose(); }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  if (!open) return null;

  return (
    <>
      <div
        className="fixed inset-0 z-40 bg-black/20"
        style={{ opacity: visible ? 1 : 0, transition: 'opacity .2s' }}
        onClick={onClose}
      />
      <div
        className="fixed left-1/2 top-1/2 z-50 w-full max-w-[600px] -translate-x-1/2 -translate-y-1/2 overflow-hidden rounded-xl bg-white shadow-[0_8px_40px_rgba(0,0,0,.16)]"
        style={{
          opacity: visible ? 1 : 0,
          transform: visible ? 'translate(-50%,-50%) scale(1)' : 'translate(-50%,-50%) scale(.96)',
          transition: 'opacity .2s, transform .2s',
          border: '1px solid #E5E7EB',
        }}
      >
        {/* Header */}
        <div className="flex items-center justify-between" style={{ padding: '16px 20px', borderBottom: '1px solid #E5E7EB' }}>
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#EFF6FF]">
              <Sparkles className="h-4 w-4 text-[#2563EB]" />
            </div>
            <div>
              <div className="text-[13.5px] font-bold text-[#111827]">AI Dashboard Summary</div>
              <div className="text-[11px] text-[#9CA3AF]">Generated by Claude</div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="flex h-7 w-7 items-center justify-center rounded-md text-[#6B7280] hover:bg-[#F3F4F6] transition-colors"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Body */}
        <div style={{ padding: '20px' }}>
          {isLoading ? (
            <div className="flex flex-col items-center gap-3 py-8">
              <div className="h-6 w-6 animate-spin rounded-full border-2 border-[#2563EB] border-t-transparent" />
              <div className="text-[12.5px] text-[#6B7280]">Analysing dashboard data…</div>
            </div>
          ) : error ? (
            <div className="rounded-[6px] border border-red-200 bg-red-50 p-4 text-[12.5px] text-red-600">
              {error}
            </div>
          ) : (
            <div className="text-[13px] leading-relaxed text-[#374151] whitespace-pre-wrap">
              {summary}
            </div>
          )}
        </div>

        {/* Footer */}
        {!isLoading && (
          <div
            className="flex justify-end"
            style={{ padding: '12px 20px', borderTop: '1px solid #E5E7EB', background: '#F9FAFB' }}
          >
            <button
              onClick={onClose}
              className="inline-flex items-center rounded-[5px] border border-[#D1D5DB] bg-white font-semibold text-[#374151] hover:bg-[#F9FAFB] transition-all"
              style={{ padding: '5px 12px', fontSize: 12 }}
            >
              Close
            </button>
          </div>
        )}
      </div>
    </>
  );
}
